name: Webpage Deploy

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'

    - name: Build Project
      run: |
        npm install
        CI=false npm run build

    - name: Sync files
      uses: nogsantos/scp-deploy@master
      with:
        host: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        user: root
        key: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        src: ./build/*
        remote: /usr/share/nginx/html
